name: Libretro cores

on:
  workflow_dispatch:
  push:
    paths: 'src/libretro/**'
  pull_request:
    paths: 'src/libretro/**'

jobs:
  libretro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y mingw-w64
      
      # - name: Clone aarch64 toolchain
      #   run: |
      #     git clone --depth 1 https://github.com/RMerl/am-toolchains.git
      #     echo "TOOLCHAIN ready at ./am-toolchains/brcm-arm-hnd/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin"

      #     mkdir -p /home/runner/toolchain
      #     cp -r am-toolchains/brcm-arm-hnd/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin /home/runner/toolchain/

      - name: Clone toolchain and setup
        run: |
          git clone --depth 1 https://github.com/RMerl/am-toolchains.git
          mkdir -p /home/runner/toolchain
          cp -r am-toolchains/brcm-arm-hnd/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/* /home/runner/toolchain/
          chmod +x /home/runner/toolchain/bin/*

      - name: Patch .br_real issue
        run: |
          for bin in gcc g++ ar as ld nm; do
            real="/home/runner/toolchain/bin/aarch64-buildroot-linux-gnu-${bin}.br_real"
            if [ -f "$real" ]; then
              mv "$real" "/home/runner/toolchain/bin/aarch64-buildroot-linux-gnu-${bin}.real"
              echo -e "#!/bin/bash\n/home/runner/toolchain/bin/aarch64-buildroot-linux-gnu-${bin}.real \"\$@\"" > "/home/runner/toolchain/bin/aarch64-buildroot-linux-gnu-${bin}"
              chmod +x "/home/runner/toolchain/bin/aarch64-buildroot-linux-gnu-${bin}"
            fi
          done

      - name: Symlink libmpc.so.3
        run: |
          ln -sf /home/runner/toolchain/lib/libmpc.so.3.0.0 /home/runner/toolchain/lib/libmpc.so.3

      - name: build
        run: |
          export LD_LIBRARY_PATH=/home/runner/toolchain/lib:$LD_LIBRARY_PATH
          export PATH=/home/runner/toolchain/bin:$PATH
          cd src/libretro && make
          find . -name "*.o" -delete
          platform=unix CC=/home/runner/toolchain/bin/aarch64-buildroot-linux-gnu-gcc CXX=/home/runner/toolchain/bin/aarch64-buildroot-linux-gnu-g++ make


      - name: Compute commit short SHA
        id: shortsha
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          branch=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})
          sanitized_branch=$(echo "$branch" | sed 's/[":<>|*?\\\/\r\n]//g')
          echo "branch=$sanitized_branch" >> "$GITHUB_ENV"
          echo "Branch: ${{ env.branch }}"
          echo "Sha: ${{ env.sha_short }}"
      - uses: actions/upload-artifact@v4
        with:
          name: freej2me_libretro-${{ env.branch }}-${{ env.sha_short }}
          path: |
            src/libretro/freej2me_libretro.so
            src/libretro/freej2me_libretro.dll
